// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int TripId { get; set; }

    public int PassengerId { get; set; }

    public byte SeatCount { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; }

    public DateTime BookingTime { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Passenger { get; set; }

    public virtual Trip Trip { get; set; }
}