// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int? TripId { get; set; }

    public int FromUserId { get; set; }

    public int ToUserId { get; set; }

    public string MessageText { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public virtual User FromUser { get; set; }

    public virtual User ToUser { get; set; }

    public virtual Trip Trip { get; set; }
}