// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int ReporterId { get; set; }

    public int ReportedUserId { get; set; }

    public int? TripId { get; set; }

    public string Reason { get; set; }

    public string Details { get; set; }

    public string Status { get; set; }

    public int? AdminId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Admin Admin { get; set; }

    public virtual User ReportedUser { get; set; }

    public virtual User Reporter { get; set; }

    public virtual Trip Trip { get; set; }
}