// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class Route
{
    public int RouteId { get; set; }

    public int UserId { get; set; }

    public string PickupLocation { get; set; }

    public string DropoffLocation { get; set; }

    public bool IsRoundTrip { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}