// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class Trip
{
    public int TripId { get; set; }

    public int DriverId { get; set; }

    public int? VehicleId { get; set; }

    public string PickupLocation { get; set; }

    public string DropoffLocation { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public byte SeatTotal { get; set; }

    public byte SeatAvailable { get; set; }

    public decimal PricePerSeat { get; set; }

    public decimal? PriceFullRide { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User Driver { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Vehicle Vehicle { get; set; }
}