// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string? PhoneNumber { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string StudentId { get; set; }

    public string University { get; set; }

    public bool GmailVerified { get; set; }

    public string Introduce { get; set; }

    public bool PhoneVerified { get; set; }

    public decimal RatingAverage { get; set; }

    public bool IsActive { get; set; }

    public bool IsVip { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }

    public string? Avatar { get; set; }

    public string? DriverLicenseNumber { get; set; }

    public string? DriverLicenseImage { get; set; }

    public string? CitizenId { get; set; }

    public string? CitizenIdImage { get; set; }

    public bool? DriverLicenseVerified { get; set; }

    public bool? CitizenIdVerified { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Message> MessageFromUsers { get; set; } = new List<Message>();

    public virtual ICollection<Message> MessageToUsers { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PasswordResetToken> PasswordResetTokens { get; set; } = new List<PasswordResetToken>();

    public virtual ICollection<Report> ReportReportedUsers { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportReporters { get; set; } = new List<Report>();

    public virtual ICollection<Review> ReviewFromUsers { get; set; } = new List<Review>();

    public virtual ICollection<Review> ReviewToUsers { get; set; } = new List<Review>();

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public virtual ICollection<UserVoucher> UserVouchers { get; set; } = new List<UserVoucher>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();

    public virtual Wallet Wallet { get; set; }
}