// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalRepository.Models;

public partial class UserVoucher
{
    public int UserVoucherId { get; set; }

    public int UserId { get; set; }

    public int VoucherId { get; set; }

    public bool IsUsed { get; set; }

    public DateTime? UsedAt { get; set; }

    public DateTime GrantedAt { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}